---
version: 0.2

env:
  variables:
    IMAGE_TAG: latest
phases:
  install:
    runtime-versions:
      docker: 19
  pre_build:
    commands:
      - echo logging in to AWS ECR...
      - docker login --username drepute --password $DOCKER_PASSWORD
      - $(aws ecr get-login --no-include-email --region us-east-1)
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo build Docker image on `date`
      - docker build -t $SERVICE_NAME:$IMAGE_TAG .
      - docker tag $SERVICE_NAME:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo build Docker image complete `date`
      - echo push latest Docker images to ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Writing image definitions file..."
      - printf '[{"name":"%s", "imageUri":"%s"}]' $SERVICE_NAME $REPOSITORY_URI:$IMAGE_TAG
        > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
