---
version: "3.9"

services:
  discord-bot-server:
    container_name: discord-bot-server
    image: discord-bot
    environment:
      - NODE_ENV=dev
      - AWS_DEFAULT_REGION=us-east-1
    env_file: .env
    entrypoint: node index.js
    networks:
      - service_mesh

networks:
  service_mesh:
    external: true
