---
name: Continuous integration

on:
  push:
    tags:
      - "**"

jobs:
  build:
    name: Trigger AWSCodePipeline
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Trigger Pipeline
        id: trigger-pipeline
        run:
          aws codepipeline start-pipeline-execution --name ${{ secrets.PIPELINE_NAME }}

